### ISSUE TITLE
CP chain counter is often incorrect

### ISSUE THREAD

**Issue by lenonk** [Shinzaku/Points#7]
I tried to capture it in a screen shot, but it's almost impossible.  In the screen shot below, which is the same one from the other issue, at the time of the kill, the counter had dropped to 0 seconds.  It reset as soon as the mob was killed.
![Screenshot_20220112_183315](https://user-images.githubusercontent.com/1181733/149245076-16b72719-18fd-4f1e-93ae-f05eaa6fea52.png)

**Comment by Shinzaku** [comment]
Unfortunately, it's ticking down to 0 due to the chain timer.
They're not 100% accurate, and until we have concrete data from Square Enix on chain timing I'm leaving them at the highest known value for high chains (60s for exp and 30s for CP)
Sorry about that; They do update to the latest chain # when a packet comes in with latest chain number.

Would need extensive testing from the community otherwise; I am contemplating on just toggling the timers off
